/**
 * Demo avatar fixtures for /api/explore.
 *
 * These appear in the marketplace + 3D viewer to demonstrate the platform with
 * a curated catalogue of public-domain glTF assets:
 *   - Khronos glTF Sample Assets         (CC-BY 4.0)
 *   - three.js example models            (MIT)
 *   - On-disk starter avatars            (shipped with three.ws)
 *
 * Generated by scripts/gen-demo-avatars.mjs from a verified GLB URL list —
 * every entry has been HEAD-checked for 200 + correct Content-Type. Edit the
 * generator, not this file, when adding sources.
 *
 * IDs prefixed with `avatar_demo_` so they never collide with DB UUIDs.
 */

import { env } from './env.js';

function demoItem({ id, slug, name, description, tags, glbUrl, image, sortDate, attribution, author }) {
	const explicitGlb = glbUrl;
	const finalGlb = explicitGlb.startsWith('http')
		? explicitGlb
		: `${env.APP_ORIGIN}${explicitGlb}`;
	return {
		kind: 'avatar',
		sortDate,
		avatarId: id,
		slug,
		name,
		description,
		image,
		glbUrl: finalGlb,
		has3d: true,
		tags,
		createdAt: sortDate,
		viewerUrl: `/avatars/${id}`,
		attribution,
		author,
	};
}

export const DEMO_AVATARS = [
	demoItem({ id: "avatar_demo_disk_cz", slug: "demo-cz", name: "CZ", description: "CZ — stylized humanoid with idle pose, ready for chat overlays.", tags: ["humanoid","character","community"], glbUrl: "https://three.ws/avatars/cz.glb", image: null, sortDate: "2025-04-01T00:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_ansem", slug: "demo-ansem", name: "Ansem", description: "Ansem — trader persona for chart-watchers and crypto Twitter.", tags: ["humanoid","community","trader"], glbUrl: "https://three.ws/avatars/default.glb", image: null, sortDate: "2025-03-31T23:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_boss", slug: "demo-boss", name: "Boss", description: "Boss — for the one running the room. Soldier rig with locomotion.", tags: ["humanoid","rigged","animated","community"], glbUrl: "https://three.ws/animations/soldier.glb", image: null, sortDate: "2025-03-31T22:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_vernington", slug: "demo-vernington", name: "Vernington", description: "Vernington — the senior of the Vern lineage.", tags: ["humanoid","community"], glbUrl: "https://three.ws/avatars/default.glb", image: null, sortDate: "2025-03-31T21:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_saga", slug: "demo-saga", name: "Saga", description: "Saga — mobile-native, expressive robot rig with idle, walk, jump, dance clips.", tags: ["robot","animated","rigged","community"], glbUrl: "https://three.ws/animations/robotexpressive.glb", image: null, sortDate: "2025-03-31T20:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_claude", slug: "demo-claude", name: "Claude", description: "Claude — calm, thoughtful AI persona.", tags: ["humanoid","community","ai"], glbUrl: "https://three.ws/avatars/default.glb", image: null, sortDate: "2025-03-31T19:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_3d", slug: "demo-3d", name: "3D", description: "3D — meta avatar representing the platform itself.", tags: ["humanoid","community","meta"], glbUrl: "https://three.ws/avatars/default.glb", image: null, sortDate: "2025-03-31T18:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_ai", slug: "demo-ai", name: "AI", description: "AI — generic agent stand-in, expressive robot rig.", tags: ["robot","animated","rigged","community","ai"], glbUrl: "https://three.ws/animations/robotexpressive.glb", image: null, sortDate: "2025-03-31T17:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_agent", slug: "demo-agent", name: "Agent", description: "Agent — operative ready for autonomous on-chain work.", tags: ["humanoid","rigged","animated","community","agent"], glbUrl: "https://three.ws/animations/soldier.glb", image: null, sortDate: "2025-03-31T16:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_vern", slug: "demo-vern", name: "Vern", description: "Vern — base form, before the Vernington promotion.", tags: ["humanoid","community"], glbUrl: "https://three.ws/avatars/default.glb", image: null, sortDate: "2025-03-31T15:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_crossinger", slug: "demo-crossinger", name: "Crossinger", description: "Crossinger — chain-hopper, multi-network identity.", tags: ["humanoid","community"], glbUrl: "https://three.ws/avatars/default.glb", image: null, sortDate: "2025-03-31T14:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_spartian", slug: "demo-spartian", name: "Spartian", description: "Spartian — disciplined, armored, never folds.", tags: ["humanoid","rigged","animated","community"], glbUrl: "https://three.ws/animations/soldier.glb", image: null, sortDate: "2025-03-31T13:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
	demoItem({ id: "avatar_demo_disk_test", slug: "demo-test", name: "Tester", description: "Tester — kicks the tires on every release before anyone else.", tags: ["humanoid","community"], glbUrl: "https://three.ws/avatars/default.glb", image: null, sortDate: "2025-03-31T12:00:00.000Z", attribution: {"handle":"three.ws","displayName":"three.ws starter","url":"https://three.ws","license":"CC-BY 4.0"}, author: {"handle":"three.ws","displayName":"three.ws starter","profileUrl":"https://three.ws"} }),
];
