// Generated by @three-ws/witness from a real user session.
// Report:  Download does nothing in the studio
// Source:  feedback report e2e-demo
// Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/148.0.7778.96 Safari/537.36
// Replay confidence: 85/100. Every step is anchored to a stable handle.
//
// This test asserts the FAILURE IS GONE, so it is red until the bug is fixed.
// What the visitor did:
//   Open /broken.html
//   Click the button [export]
//   Type 12 characters into the input #model-name
//   Click the button labelled "Download the GLB"
//   The page threw: TypeError: window.exportGLB is not a function
//   The request failed: POST /api/export-that-fails -> 500

import { test, expect } from '@playwright/test';
test.describe('witness repro', () => {
	test.use({ viewport: { width: 390, height: 844 }, locale: 'en-GB' });
	test('Download does nothing in the studio', async ({ page }) => {
	// Collect the same classes of failure the visitor hit, so the assertions
	// below fail for the reported reason and not for an unrelated one.
	const pageErrors = [];
	const failedRequests = [];
	page.on('pageerror', (err) => pageErrors.push(`${err.name}: ${err.message}`));
	page.on('response', (res) => {
		if (res.status() >= 400) failedRequests.push(`${res.request().method()} ${new URL(res.url()).pathname} -> ${res.status()}`);
	});

	await page.goto('http://localhost:4711/broken.html');
	await page.getByTestId("export").click();
	await page.locator("#model-name").fill('xxxxxxxxxxxx'); // visitor typed 12 text character(s)
	await page.getByLabel("Download the GLB").click();

	// The session threw. The reported failure was:
	//   TypeError: window.exportGLB is not a function
	expect(pageErrors, `the page threw during the reported flow`).toEqual([]);
	// The session saw these requests fail:
	//   POST /api/export-that-fails -> 500
	expect(failedRequests, `a request failed during the reported flow`).toEqual([]);
	});
});
