// @ts-check
// GET /api/cron/changelog-push — automatic changelog delivery to the holder
// Telegram channel.
//
// Runs every 20 minutes. Reads the changelog feed baked into the running
// image (public/changelog.json, regenerated by every deploy build), diffs it
// against DB state, and posts anything new to the holders' Telegram channel.
// Because the feed ships inside the image, entries go out shortly after the
// deploy that made them live, with no manual `npm run changelog:push` step.
//
// X.com delivery is retired (owner directive 2026-07-18). The X lane
// (pushXLane) and its manual script stay in the tree but are no longer
// invoked. Telegram is the only automatic holder channel; the on-site
// changelog, RSS feed, and GitHub CHANGELOG.md carry the rest.
//
// A lane whose credentials are absent reports { skipped: 'not_configured' }.
//   Telegram: TELEGRAM_BOT_TOKEN + TELEGRAM_CHANGELOG_CHAT_ID
//
// A DB lock (app_settings) keeps overlapping ticks from double-posting.
// Selection, pacing, caps, and message formats live in
// api/_lib/changelog-push.js; the manual scripts in scripts/changelog-*.mjs
// remain for previews (--dry-run) and backfills only.

import { error, json, method, wrapCron } from '../_lib/http.js';
import { env } from '../_lib/env.js';
import { constantTimeEquals } from '../_lib/crypto.js';
import { acquireLock, releaseLock, loadFeed, pushTelegramLane } from '../_lib/changelog-push.js';

function requireCron(req, res) {
	const secret = process.env.CRON_SECRET || env.CRON_SECRET;
	if (!secret) {
		error(res, 503, 'not_configured', 'CRON_SECRET unset');
		return false;
	}
	const auth = req.headers['authorization'] || '';
	const presented = auth.startsWith('Bearer ') ? auth.slice(7) : '';
	if (!constantTimeEquals(presented, secret)) {
		error(res, 401, 'unauthorized', 'invalid cron secret');
		return false;
	}
	return true;
}

export default wrapCron(async (req, res) => {
	if (!method(req, res, ['GET'])) return;
	if (!requireCron(req, res)) return;

	if (!(await acquireLock())) {
		json(res, 200, { ok: true, skipped: 'locked' });
		return;
	}

	let feed;
	try {
		feed = loadFeed();
	} catch (err) {
		await releaseLock().catch(() => {});
		error(res, 500, 'feed_unreadable', String(err?.message || err));
		return;
	}

	try {
		// X.com delivery is retired (owner directive 2026-07-18). Holder delivery
		// runs on Telegram only; the on-site changelog + RSS + GitHub feed carry
		// the rest. The X lane and its manual script stay in the tree but are no
		// longer invoked by the cron.
		const telegram = await pushTelegramLane(feed);
		const failed = Boolean(telegram.error);
		if (failed) console.warn('[cron] changelog-push lane error', { telegram });
		json(res, failed ? 502 : 200, { ok: !failed, telegram, x: { skipped: 'retired' } });
	} finally {
		await releaseLock().catch(() => {});
	}
});
