import { chromium } from 'playwright';
import { mkdirSync } from 'fs';
const OUT = '/workspaces/three.ws/scratch/home-v2-shots';
mkdirSync(OUT, { recursive: true });
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errs = [];
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
page.on('pageerror', (e) => errs.push('PAGEERROR: ' + e.message));
console.log('→ loading /home-v2');
await page.goto('http://localhost:3000/home-v2', { waitUntil: 'domcontentloaded', timeout: 60_000 });
await page.waitForSelector('#hv2-chips .hv2-chip', { timeout: 10_000 });
const chipCount = await page.$$eval('#hv2-chips .hv2-chip', (els) => els.length);
console.log(`✓ chip strip rendered, ${chipCount} chips`);
console.log(`✓ tryme visible: ${await page.isVisible('#hv2-tryme')}`);
await page.waitForFunction(() => {
  const c = document.getElementById('hero-avatar');
  return c && getComputedStyle(c).opacity === '1';
}, { timeout: 30_000 }).catch(() => console.log('… hero canvas opacity never reached 1'));
await page.screenshot({ path: `${OUT}/01-hero-initial.png` });
console.log(`✓ saved ${OUT}/01-hero-initial.png`);
console.log('→ clicking Wave chip');
await page.click('.hv2-chip[data-anim="wave"]');
await page.waitForTimeout(1200);
console.log(`✓ counter: ${await page.textContent('#hv2-counter-num')}`);
console.log(`✓ tryme hidden: ${await page.$eval('#hv2-tryme', (el) => el.classList.contains('is-hidden'))}`);
await page.screenshot({ path: `${OUT}/02-after-wave.png` });
console.log(`✓ saved ${OUT}/02-after-wave.png`);
console.log('→ clicking Random');
await page.click('.hv2-chip[data-anim="__random"]');
await page.waitForTimeout(1500);
await page.screenshot({ path: `${OUT}/03-after-random.png` });
console.log(`✓ saved ${OUT}/03-after-random.png`);
console.log('\nconsole errors:', errs.length === 0 ? '(none)' : '');
for (const e of errs) console.log('  ' + e);
await browser.close();
console.log('✓ done');
