// /gestures: the agent gesture vocabulary, previewed live.
//
// Three things are on this page, all of them derived rather than restated:
//
//   • the slot grid, from SLOTS + DEFAULT_ANIMATION_MAP (src/runtime/animation-slots.js)
//   • the hint table, from /agent-hints.json (generated by scripts/build-agent-hints.mjs
//     out of the shipped skill definitions, so the attribution cannot go stale)
//   • the /walk gesture layers, from GESTURES (src/animation-state-machine.js)
//
// The 3D preview reuses the gallery's shared engine: one renderer, one avatar,
// moved into the stage on demand. Nothing 3D loads until the first gesture is
// played, so the page paints without a GL context.

import { SLOTS, DEFAULT_ANIMATION_MAP, HINT_ALIASES } from './runtime/animation-slots.js';
import { GESTURES, GESTURE_NAMES } from './animation-state-machine.js';
import { curate, CATEGORIES } from './animation-presets.js';

const MANIFEST_URL = '/animations/manifest.json';
const HINTS_URL = '/agent-hints.json';
const THUMB_BASE = '/animations/thumbs';

/** What each slot means, in one line. Prose, not derivable from the map. */
const SLOT_NOTES = {
	idle: 'The resting loop. Always playing underneath everything else.',
	wave: 'Greeting, and the first gesture most agents ever play.',
	nod: 'Acknowledging. Fired when a model finishes loading.',
	shake: 'Refusing. The only baked head-shake clip in the library.',
	think: 'Reasoning. Fired while a skill or a load is in flight.',
	celebrate: 'A win: a clean validation, a settled payment, a launch.',
	concern: 'Something failed. Paired with a downward gaze.',
	bow: 'Thanks. The one slot with no dedicated clip yet.',
	point: 'Deictic: referring to a thing on screen. Also the generic action gesture.',
	shrug: 'Uncertainty. Overlays locomotion on /walk, so an avatar can shrug mid-stride.',
	fidget: 'Idle restlessness for a long wait.',
	dance: 'Celebration with the whole body. The club stage books these by name.',
	inspect: 'Reading data. The most-declared hint in the skill catalog.',
	present: 'Showing a result off.',
	sign: 'Authorizing a wallet signature.',
	curiosity: 'Scanning, looking around, alert.',
	patience: 'Waiting on long-running work.',
	manipulate: 'Handling a scene object.',
	conjure: 'Creating something from nothing.',
};

/** Slots whose clip is an approximation rather than a match. */
const APPROXIMATE = new Set(['bow']);

const $ = (sel, root = document) => root.querySelector(sel);
const el = (role, root = document) => root.querySelector(`[data-role="${role}"]`);

const state = {
	manifest: [],
	byName: new Map(),
	hints: null,
	slot: null,
	clip: null, // the clip currently staged (default or override)
	preview: null, // lazily imported AnimationLivePreview
	paused: false,
	agents: null, // null = not fetched yet, [] = signed out or no agents
	agentsLoading: false,
};

/* ── data ──────────────────────────────────────────────────────────────── */

async function fetchJson(url) {
	const res = await fetch(url, { headers: { accept: 'application/json' } });
	if (!res.ok) throw new Error(`${url} responded ${res.status}`);
	return res.json();
}

async function loadManifest() {
	const grid = el('grid');
	const errorBox = el('grid-error');
	grid.setAttribute('aria-busy', 'true');
	errorBox.hidden = true;
	try {
		const manifest = await fetchJson(MANIFEST_URL);
		state.manifest = Array.isArray(manifest) ? manifest : [];
		state.byName = new Map(state.manifest.map((c) => [c.name, c]));
		renderGrid();
		renderOverrideOptions();
		renderStats();
		applyDeepLink();
	} catch (err) {
		grid.innerHTML = '';
		grid.setAttribute('aria-busy', 'false');
		errorBox.hidden = false;
		el('grid-error-detail').textContent = err?.message || String(err);
	}
}

async function loadHints() {
	const host = el('hints');
	try {
		state.hints = await fetchJson(HINTS_URL);
		renderHints();
		renderStats();
	} catch (err) {
		// The hint table is supporting detail: the vocabulary above it still works,
		// so degrade to a readable note instead of an error state for the page.
		host.innerHTML = `<div class="gv-hints-loading">The skill map did not load (${escapeHtml(
			err?.message || String(err),
		)}). Every hint is also listed in <a href="/docs/animations">docs/animations</a>.</div>`;
	}
}

/* ── render ────────────────────────────────────────────────────────────── */

function escapeHtml(s) {
	return String(s).replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);
}

function renderStats() {
	el('stat-slots').textContent = String(SLOTS.length);
	el('stat-clips').textContent = String(state.manifest.length || '-');
	el('stat-hints').textContent = String(state.hints?.hints?.length ?? '-');
	el('stat-skills').textContent = String(state.hints?.total_skills ?? '-');
}

function cardHtml(slot) {
	const clip = DEFAULT_ANIMATION_MAP[slot];
	const def = state.byName.get(clip);
	const label = def?.label || clip;
	const icon = def?.icon || '🎞️';
	const badge = APPROXIMATE.has(slot)
		? '<span class="gv-badge gv-badge--warn" title="No dedicated clip for this slot yet">approx</span>'
		: def?.loop
			? '<span class="gv-badge" title="This clip loops">loop</span>'
			: '';
	// The note is rendered, not hidden behind a `title` tooltip: a browser
	// tooltip needs a second of hover, never appears on touch, and is the
	// difference between "what does `conjure` mean" being answered and not.
	return `
		<button type="button" class="gv-card" role="listitem" data-slot="${escapeHtml(slot)}"
			aria-current="false">
			<span class="gv-card-thumb">
				<span class="gv-card-thumb-fallback" aria-hidden="true">${icon}</span>
				<img src="${THUMB_BASE}/${encodeURIComponent(clip)}.webp" alt=""
					loading="lazy" decoding="async" width="480" height="480" />
				${badge}
			</span>
			<span class="gv-card-body">
				<span class="gv-card-slot">${escapeHtml(slot)}</span>
				<span class="gv-card-clip">${escapeHtml(label)}</span>
				<span class="gv-card-note">${escapeHtml(SLOT_NOTES[slot] || '')}</span>
			</span>
		</button>`;
}

function renderGrid() {
	const grid = el('grid');
	grid.innerHTML = SLOTS.map(cardHtml).join('');
	grid.setAttribute('aria-busy', 'false');
	// The clip's emoji stands in until its poster paints, then gets out of the
	// way: leaving both would stamp an emoji over the avatar. A poster that never
	// loads keeps the emoji and drops the empty image box.
	for (const img of grid.querySelectorAll('.gv-card-thumb img')) {
		const fallback = img.previousElementSibling;
		const settle = () => fallback?.remove();
		if (img.complete && img.naturalWidth > 0) settle();
		else {
			img.addEventListener('load', settle, { once: true });
			img.addEventListener('error', () => img.remove(), { once: true });
		}
	}
}

function renderHints() {
	const rows = state.hints?.hints || [];
	const head = `
		<div class="gv-row gv-row--head">
			<span>Hint</span><span>Slot</span><span>Clip</span><span>Skills</span>
		</div>`;
	const body = rows
		.map((row) => {
			const alias = HINT_ALIASES[row.hint] ? ' <span class="gv-arrow">(alias)</span>' : '';
			const skills = row.skills
				.map((s) => `<code>${escapeHtml(s)}</code>`)
				.join('');
			return `
				<div class="gv-row">
					<span class="gv-mono">${escapeHtml(row.hint)}${alias}</span>
					<span class="gv-mono">${escapeHtml(row.slot)}</span>
					<span class="gv-mono">${escapeHtml(row.clip)}</span>
					<span class="gv-count">${row.skills.length}</span>
				</div>
				<details>
					<summary>Show the ${row.skills.length} skill${row.skills.length === 1 ? ' that declares' : 's that declare'} <code>${escapeHtml(row.hint)}</code></summary>
					<div class="gv-hints-skills">${skills}</div>
				</details>`;
		})
		.join('');
	el('hints').innerHTML = head + body;
}

function renderLayers() {
	const head = `
		<div class="gv-row gv-row--head">
			<span>Gesture</span><span>Clip</span><span>Layer</span><span>Hold</span>
		</div>`;
	const body = GESTURE_NAMES.map((name) => {
		const g = GESTURES[name];
		return `
			<div class="gv-row">
				<span class="gv-mono">${escapeHtml(name)}</span>
				<span class="gv-mono">${escapeHtml(g.clip)}</span>
				<span class="gv-mono">${g.layer}</span>
				<span class="gv-count">${g.loop ? 'held' : 'one-shot'}</span>
			</div>`;
	}).join('');
	el('layers').innerHTML = head + body;
}

function renderOverrideOptions() {
	const select = el('override-select');
	const { groups } = curate(state.manifest);
	const order = new Map(CATEGORIES.map((c, i) => [c.key, i]));
	const sorted = [...groups].sort((a, b) => (order.get(a.key) ?? 99) - (order.get(b.key) ?? 99));
	select.innerHTML = sorted
		.map(
			(g) => `<optgroup label="${escapeHtml(`${g.icon} ${g.label}`)}">${g.items
				.map(
					(item) =>
						`<option value="${escapeHtml(item.name)}">${escapeHtml(item.label || item.name)}</option>`,
				)
				.join('')}</optgroup>`,
		)
		.join('');
}

function renderOverride() {
	const box = el('override');
	if (!state.slot) {
		box.hidden = true;
		return;
	}
	box.hidden = false;
	el('override-slot').textContent = state.slot;
	el('override-select').value = state.clip;
	const json = JSON.stringify({ edits: { animations: { [state.slot]: state.clip } } }, null, 2);
	$('code', el('override-code')).textContent = json;
	const isDefault = state.clip === DEFAULT_ANIMATION_MAP[state.slot];
	el('override-reset').disabled = isDefault;
	renderApply();
}

/* ── apply to an agent ─────────────────────────────────────────────────── */

/**
 * The signed-in user's agents. A 401 is the ordinary signed-out case, not an
 * error: the page is public and everything except this panel works without an
 * account. Runs once, lazily, the first time a gesture is selected.
 */
async function loadAgents() {
	if (state.agents !== null || state.agentsLoading) return;
	state.agentsLoading = true;
	try {
		const res = await fetch('/api/agents', {
			credentials: 'include',
			headers: { accept: 'application/json' },
		});
		state.agents = res.ok ? ((await res.json()).agents ?? []) : [];
	} catch {
		state.agents = [];
	} finally {
		state.agentsLoading = false;
		renderApply();
	}
}

function renderApply() {
	const panel = el('apply');
	const signedOut = el('apply-signedout');
	if (!state.slot) {
		panel.hidden = true;
		signedOut.hidden = true;
		return;
	}
	const agents = state.agents;
	if (agents === null) {
		// Still loading: show neither panel rather than flashing the signed-out
		// call to action at a user who is in fact signed in.
		panel.hidden = true;
		signedOut.hidden = true;
		return;
	}
	if (!agents.length) {
		panel.hidden = true;
		signedOut.hidden = false;
		return;
	}
	signedOut.hidden = true;
	panel.hidden = false;

	const select = el('apply-select');
	if (select.dataset.filled !== String(agents.length)) {
		select.dataset.filled = String(agents.length);
		select.innerHTML = agents
			.map((a) => `<option value="${escapeHtml(a.id)}">${escapeHtml(a.name || a.id)}</option>`)
			.join('');
	}
	// Saving the default is a no-op the server would accept; say so instead.
	const isDefault = state.clip === DEFAULT_ANIMATION_MAP[state.slot];
	const save = el('apply-save');
	save.disabled = false;
	save.textContent = isDefault ? 'Clear this override' : 'Save to agent';
}

async function applyToAgent() {
	const save = el('apply-save');
	const status = el('apply-status');
	const agentId = el('apply-select').value;
	const agent = (state.agents || []).find((a) => a.id === agentId);
	if (!agentId || !state.slot) return;

	// Merge over the agent's existing overrides so saving one gesture never
	// drops another. Selecting the platform default removes the entry.
	const current = { ...(agent?.meta?.edits?.animations || {}) };
	if (state.clip === DEFAULT_ANIMATION_MAP[state.slot]) delete current[state.slot];
	else current[state.slot] = state.clip;

	save.disabled = true;
	status.textContent = 'Saving…';
	status.className = 'gv-apply-status';
	try {
		const { apiFetch } = await import('./api.js');
		const res = await apiFetch(`/api/agents/${agentId}/animations`, {
			method: 'PUT',
			headers: { 'content-type': 'application/json' },
			credentials: 'include',
			body: JSON.stringify({ animationSlots: current }),
		});
		if (!res.ok) {
			const body = await res.json().catch(() => ({}));
			throw new Error(body.error_description || body.error || `HTTP ${res.status}`);
		}
		const saved = await res.json();
		// Keep the local copy in step so a second save merges against the truth.
		if (agent) agent.meta = { ...(agent.meta || {}), edits: { ...(agent.meta?.edits || {}), animations: saved.animationSlots || {} } };
		const count = Object.keys(saved.animationSlots || {}).length;
		status.innerHTML = `Saved. <a href="/a/${escapeHtml(agentId)}">Open ${escapeHtml(agent?.name || 'the agent')}</a> to see it, ${count} override${count === 1 ? '' : 's'} in total.`;
		status.className = 'gv-apply-status is-ok';
	} catch (err) {
		status.textContent = `Could not save: ${err.message}`;
		status.className = 'gv-apply-status is-err';
	} finally {
		save.disabled = false;
	}
}

/* ── preview ───────────────────────────────────────────────────────────── */

function setStageState(name, detail = '') {
	el('stage-empty').hidden = name !== 'empty';
	el('stage-loading').hidden = name !== 'loading';
	el('stage-error').hidden = name !== 'error';
	if (name === 'error' && detail) el('stage-error-title').textContent = detail;
}

async function getPreview() {
	if (!state.preview) {
		const mod = await import('./animations-live-preview.js');
		state.preview = mod.getLivePreview();
	}
	return state.preview;
}

async function play(slot, clip = DEFAULT_ANIMATION_MAP[slot]) {
	state.slot = slot;
	state.clip = clip;
	const def = state.byName.get(clip);
	el('stage-slot').textContent = slot;
	el('stage-clip').textContent = def?.label ? `${def.label} · ${clip}` : clip;
	const note = el('stage-note');
	note.textContent = SLOT_NOTES[slot] || '';
	note.hidden = !note.textContent;
	loadAgents();
	el('stage-status').textContent = `Playing ${slot}: ${def?.label || clip}`;
	for (const card of document.querySelectorAll('.gv-card[data-slot]')) {
		card.setAttribute('aria-current', String(card.dataset.slot === slot));
	}
	renderOverride();
	syncUrl();

	if (!def) {
		setStageState('error', `"${clip}" is not in the clip manifest.`);
		return;
	}

	setStageState('loading');
	el('stage-replay').disabled = true;
	el('stage-pause').disabled = true;
	try {
		const preview = await getPreview();
		await preview.play(el('stage'), {
			id: clip,
			source: 'curated',
			url: def.url,
			loop: def.loop !== false,
		});
		// A superseded play() resolves without mounting; only clear the overlay
		// when this call is still the current one.
		if (state.clip !== clip) return;
		setStageState('none');
		state.paused = false;
		el('stage-replay').disabled = false;
		el('stage-pause').disabled = false;
		el('stage-pause').setAttribute('aria-pressed', 'false');
	} catch (err) {
		if (state.clip !== clip) return;
		setStageState('error', err?.message ? `Preview failed: ${err.message}` : undefined);
	}
}

function stop() {
	state.preview?.stop();
	setStageState('empty');
	el('stage-slot').textContent = 'No gesture selected';
	el('stage-clip').innerHTML = '&nbsp;';
	el('stage-replay').disabled = true;
	// Reset the pause toggle: leaving it latched showed a play icon on a stage
	// with nothing to play.
	state.paused = false;
	const pause = el('stage-pause');
	pause.disabled = true;
	pause.setAttribute('aria-pressed', 'false');
	pause.textContent = '❙❙';
	el('stage-note').hidden = true;
	el('override').hidden = true;
	el('apply').hidden = true;
	el('apply-signedout').hidden = true;
	state.slot = null;
	state.clip = null;
	for (const card of document.querySelectorAll('.gv-card[data-slot]')) {
		card.setAttribute('aria-current', 'false');
	}
	syncUrl();
}

/* ── url state ─────────────────────────────────────────────────────────── */

function syncUrl() {
	const url = new URL(window.location.href);
	if (state.slot) url.searchParams.set('slot', state.slot);
	else url.searchParams.delete('slot');
	if (state.slot && state.clip !== DEFAULT_ANIMATION_MAP[state.slot]) {
		url.searchParams.set('clip', state.clip);
	} else {
		url.searchParams.delete('clip');
	}
	window.history.replaceState(null, '', url);
}

function applyDeepLink() {
	const params = new URLSearchParams(window.location.search);
	const slot = params.get('slot');
	if (!slot || !SLOTS.includes(slot)) return;
	const clip = params.get('clip');
	play(slot, clip && state.byName.has(clip) ? clip : DEFAULT_ANIMATION_MAP[slot]);
}

/* ── events ────────────────────────────────────────────────────────────── */

function cardAt(index) {
	const cards = [...document.querySelectorAll('.gv-card[data-slot]')];
	if (!cards.length) return null;
	const wrapped = ((index % cards.length) + cards.length) % cards.length;
	return cards[wrapped];
}

function columnsInGrid() {
	const grid = el('grid');
	const style = getComputedStyle(grid);
	return Math.max(1, style.gridTemplateColumns.split(' ').filter(Boolean).length);
}

function wire() {
	el('grid').addEventListener('click', (e) => {
		const card = e.target.closest('.gv-card[data-slot]');
		if (card) play(card.dataset.slot);
	});

	// Arrow keys walk the grid; Enter plays. Roving focus, so the browser's own
	// focus ring is the selection indicator.
	el('grid').addEventListener('keydown', (e) => {
		const card = e.target.closest('.gv-card[data-slot]');
		if (!card) return;
		const cards = [...document.querySelectorAll('.gv-card[data-slot]')];
		const i = cards.indexOf(card);
		const cols = columnsInGrid();
		const moves = { ArrowRight: 1, ArrowLeft: -1, ArrowDown: cols, ArrowUp: -cols };
		if (e.key in moves) {
			e.preventDefault();
			cardAt(i + moves[e.key])?.focus();
			return;
		}
		if (e.key === 'Home' || e.key === 'End') {
			e.preventDefault();
			cardAt(e.key === 'Home' ? 0 : cards.length - 1)?.focus();
		}
	});

	document.addEventListener('keydown', (e) => {
		if (e.key === 'Escape' && state.slot) stop();
	});

	el('grid-retry').addEventListener('click', loadManifest);
	el('stage-retry').addEventListener('click', () => {
		if (state.slot) play(state.slot, state.clip);
	});

	el('stage-replay').addEventListener('click', () => {
		if (state.slot) play(state.slot, state.clip);
	});

	el('stage-pause').addEventListener('click', async (e) => {
		const preview = await getPreview();
		state.paused = !state.paused;
		preview.setPaused(state.paused);
		e.currentTarget.setAttribute('aria-pressed', String(state.paused));
		e.currentTarget.textContent = state.paused ? '▶' : '❙❙';
		el('stage-status').textContent = state.paused ? 'Preview paused' : 'Preview playing';
	});

	el('override-select').addEventListener('change', (e) => {
		if (state.slot) play(state.slot, e.target.value);
	});

	el('override-reset').addEventListener('click', () => {
		if (state.slot) play(state.slot, DEFAULT_ANIMATION_MAP[state.slot]);
	});

	el('apply-save').addEventListener('click', applyToAgent);

	const copy = async (e) => {
		const btn = e.currentTarget;
		const text = $('code', el('override-code')).textContent;
		try {
			await navigator.clipboard.writeText(text);
			btn.textContent = 'Copied';
		} catch {
			// Clipboard is permission-gated in some browsers: select the block so
			// the user can copy it by hand instead of silently failing.
			const range = document.createRange();
			range.selectNodeContents(el('override-code'));
			const sel = window.getSelection();
			sel.removeAllRanges();
			sel.addRange(range);
			btn.textContent = 'Selected, press Cmd/Ctrl+C';
		}
		setTimeout(() => {
			btn.textContent = 'Copy JSON';
		}, 1800);
	};
	el('override-copy').addEventListener('click', copy);
	el('override-copy-2').addEventListener('click', copy);

	// Stop burning frames on a hidden tab, without stomping a pause the user
	// chose: state.paused stays the source of truth for the button.
	document.addEventListener('visibilitychange', () => {
		state.preview?.setPaused(document.hidden ? true : state.paused);
	});
}

renderLayers();
wire();
loadManifest();
loadHints();
